# docker-compose.yml
# RUN: ```docker-compose --env-file```
version: "3.7"

services:
  npm:
    build:   
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        VERSION: 2.7.3  #"${NPM_VERSION}"  # if using .env file
    image: npm:test              # provide a name and tag for the image
  # mariadb:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-mariadb
  #     args:
  #       VERSION: 10.4.15  #"${MARIADB_VERSION}"  # if using .env file
  #   image: mariadb:test


  # volumes:  # Optional, same as `docker volume create`

  # networks:  # Optional, same as `docker network create`